# Site settings
title: Mundane Programming
email: dun@stanford.edu
description: |
  A mini-site of mundane programming practice and examples.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mundaneprogramming.github.io" # the base hostname & protocol for your site
twitter_username: dancow
github_username:  mundaneprogramming

# Build settings
markdown: kramdown
